import 'package:supabase_flutter/supabase_flutter.dart';

class BinItem {
  // Supabase storage path (e.g., 'user_id/bin/image.jpg'). Used for deletion/move.
  final String storagePath;
  
  // The public URL generated by Supabase to display the image.
  final String imageUrl;

  // The file name, extracted from metadata.
  final String fileName;

  // File creation time for "Lifetime Memory" tracking.
  final DateTime dateAdded;
  
  const BinItem({
    required this.storagePath,
    required this.imageUrl,
    required this.fileName,
    required this.dateAdded,
  });

  // Factory method to create BinItem from Supabase Storage metadata (map)
factory BinItem.fromSupabaseFileObject(
  FileObject fileObject, 
  String publicUrl
) {
  // Supabase stores file creation time in 'created_at'
  final createdAtString = fileObject.createdAt; // Access property directly
  
  return BinItem(
    // Access properties directly
    storagePath: fileObject.id!, // Access ID property
    imageUrl: publicUrl,
    fileName: fileObject.name!,
    dateAdded: DateTime.parse(createdAtString!),
  );
  }
}