// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCpzODN0eLUm_Ah67-Dx9scaVOdOR4NZX8',
    appId: '1:504809133297:web:b7b0bc8050a3956a92c550',
    messagingSenderId: '504809133297',
    projectId: 'memoir-e284a',
    authDomain: 'memoir-e284a.firebaseapp.com',
    storageBucket: 'memoir-e284a.firebasestorage.app',
    measurementId: 'G-T0GHZQ68GV',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCB84R5pJBs1lyylJK1AifT7s_iIZ0SrbQ',
    appId: '1:504809133297:android:9ab2f31c695fb9a692c550',
    messagingSenderId: '504809133297',
    projectId: 'memoir-e284a',
    storageBucket: 'memoir-e284a.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBZQGWnQ0xjP4nwOfnRD0m_H34aSOFGVWY',
    appId: '1:504809133297:ios:ce03e982a2368ac592c550',
    messagingSenderId: '504809133297',
    projectId: 'memoir-e284a',
    storageBucket: 'memoir-e284a.firebasestorage.app',
    iosBundleId: 'com.example.presentation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBZQGWnQ0xjP4nwOfnRD0m_H34aSOFGVWY',
    appId: '1:504809133297:ios:ce03e982a2368ac592c550',
    messagingSenderId: '504809133297',
    projectId: 'memoir-e284a',
    storageBucket: 'memoir-e284a.firebasestorage.app',
    iosBundleId: 'com.example.presentation',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCpzODN0eLUm_Ah67-Dx9scaVOdOR4NZX8',
    appId: '1:504809133297:web:1209928268726d6e92c550',
    messagingSenderId: '504809133297',
    projectId: 'memoir-e284a',
    authDomain: 'memoir-e284a.firebaseapp.com',
    storageBucket: 'memoir-e284a.firebasestorage.app',
    measurementId: 'G-PSP9DGGT2J',
  );
}
